### PR TITLE
Track detail

### PR DESCRIPTION
**Pull request by denysgud**

### CODE REVIEW

**Comment by yurykozhenov** [comment]
Fix links

When I go to track detail page from map it goes to `http://localhost:8080/#!/places/57a4d84dca7a727c0ca59ba5`

**Comment by yurykozhenov** [comment]
When going to two different tracks it throws an error:
`"Map container is already initialized"`
and no map is showing

You can ask @helenrivne about this, she found a solution.

**Comment by yurykozhenov** [comment]
Vertical photo is too large, please fix this.

track detail photo

**Comment by denysgud** [comment]
I know solution for `"Map container is already initialized"` problem, just forgot to add in my component. :smile: :smile: :smile:

**Comment by denysgud** [comment]
I just use place detail template so I think it would be better to fix vertical photo problem in place-detail branch.

**Comment by yurykozhenov** [comment]
This closes #66

**Pull request merged**
